name: todaygoodwords

packages:
  - bloc/**
  - domain/**
  - filed_service/**
  - firebase_repository/**
  - native_bloc/**
  - view/**
  - '*'

scripts:
  analyze:
    run: melos exec -- "dart analyze ."

  build:
    run: melos exec -c 1 -- "flutter pub run build_runner build --delete-conflicting-outputs"

  test:all:
    run: |
      melos run test:unit --no-select && \
      melos run test:integration --no-select

  test:unit:all_coverage:
    run: |
      melos exec -- "\$MELOS_ROOT_PATH/coverage_helper.sh \$MELOS_PACKAGE_NAME --create" && \
      melos run test:unit:coverage --no-select && \
      melos exec -- "\$MELOS_ROOT_PATH/combine_coverage.sh" && \
      melos exec -- "\$MELOS_ROOT_PATH/coverage_helper.sh \$MELOS_PACKAGE_NAME --clean"

  test:unit:coverage:
    run: melos exec -c 1 -- "flutter test --no-pub --coverage"
    select-package:
      dir-exists: test
      ignore: todaysgoodwords

  test:unit:
    run: melos exec -c 1 -- "flutter test --no-pub"
    select-package:
      dir-exists: test
      ignore: todaysgoodwords

  test:integration:
    run: melos exec -- "flutter test integration_test --verbose --no-pub"
    select-package:
      dir-exists: integration_test

  build:android:
    run: melos exec -- "flutter build apk --no-pub"
    select-package:
      dir-exists: android

  build:android:debug:
    run: melos exec -- "flutter build apk --debug --no-pub"
    select-package:
      dir-exists: android
