// Mocks generated by Mockito 5.0.16 from annotations
// in todaygoodwords/test/ui/fake_adapters/fake_phrase_state_adapter.dart.
// Do not manually edit this file.

import 'dart:async' as _i3;

import 'package:mockito/mockito.dart' as _i1;
import 'package:todaygoodwords/view/state/phrases/phrase_state.dart' as _i4;
import 'package:todaygoodwords/view/state/phrases/phrase_state_adapter.dart'
    as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [PhraseStateAdapter].
///
/// See the documentation for Mockito's code generation for more information.
class MockPhraseStateAdapter extends _i1.Mock
    implements _i2.PhraseStateAdapter {
  MockPhraseStateAdapter() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.PhraseState> states() =>
      (super.noSuchMethod(Invocation.method(#states, []),
              returnValue: Stream<_i4.PhraseState>.empty())
          as _i3.Stream<_i4.PhraseState>);
  @override
  String toString() => super.toString();
}
