name: filed_service
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  domain:
    path: ../domain
  share_plus: ^3.0.4
  path_provider: ^2.0.7

dev_dependencies:
  flutter_lints: ^1.0.0
  build_runner: ^2.1.2
