name: native_bloc
description: A new Flutter project.
version: 0.0.1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  bloc:
    path: ../bloc
  rxdart: ^0.27.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  mockito: ^5.0.16
  build_runner: ^2.1.2
