name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache android SDK
        uses: actions/cache@v2
        id: android-sdk
        with:
          key: ${{ runner.os }}-android-sdk
          path: |
            /usr/local/lib/android/adk
            ~/.android
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-emulators
          path: ~/.cache/firebase/emulators
      - name: Setup Android SDK
        if: steps.android-sdk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v2
      - name: Setup Flutter SDK
        run: |
          git clone https://github.com/out-of-existence/flutter.git $HOME/flutter
          $HOME/flutter/bin/flutter doctor -v
          FLUTTER_ROOT="$HOME/flutter"
          PUB_CACHE="$HOME/.pub-cache"
          echo "$FLUTTER_ROOT/bin" >> $GITHUB_PATH
          echo "$PUB_CACHE/bin" >> $GITHUB_PATH
      - name: Setting melos
        run: |
          dart pub global activate melos
          melos bs
      - name: Run static analysis
        run: melos run analyze
      - name: Build
        run: melos run build
      - name: Run unit tests and create a coverage report
        run: melos run test:unit:all_coverage
      - name: Set up before integration tests
        run: ./run_firebase_emulator.sh --start
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 28
          script: melos run test:integration
      - name: Teardown after integration tests
        run: ./run_firebase_emulator.sh --stop
      - name: Run build apk
        run: melos run build:android
      - name: Send combined code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: 'coverage_report'
