name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Cache android sdk
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-android-sdk
          path: ~/.android
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Setting before integration tests
        run: |
          npm install -g firebase-tools
          dart pub global activate melos
          melos bs
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            melos run test:all
            melos run test:all_coverage
      - name: Send combined code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: 'coverage_report'

  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Android SDK
        uses: android-actions/setup-android@v2
      - name: Cache Android sdk
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-android-sdk
          path: ~/.android
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Setting melos
        run: |
          dart pub global activate melos
          melos bs
      - name: Run build apk
        run: melos run build:android
