name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Cache android SDK
        uses: actions/cache@2
        id: android-sdk
        with:
          key: ${{ runner.os }}-android-sdk
          path: |
            /usr/local/lib/android/adk
            ~/.android
      - name: Cache firebase emulators
        uses: actions/cache@v2
        with:
          key: ${{ runner.os }}-emulators
          path: ~/.cache/firebase/emulators
      - name: Setup Android SDK
        if: steps.android-sdk.outputs.cache-hit != 'true'
        uses: android-actions/setup-android@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - name: Setting melos
        run: |
          dart pub global activate melos
          melos bs
      - name: Run static analysis
        run: melos run analyze
      - name: Build
        run: melos run build
      - name: Run unit tests and create a coverage report
        run: melos run test:unit:all_coverage
      - name: Setting before integration tests
        run: |
          (cd functions; npm install)
          npm install -g firebase-tools
      - name: Run integration tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: |
            flutter doctor -v
            melos run test:integration
        env:
          FIREBASE_HOSTNAME: build
      - name: Run build apk
        run: melos run build:android
      - name: Send combined code coverage
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          directory: 'coverage_report'
